---
title: "TCDM"
output: html_document
date: "`r Sys.Date()`"
---
```{r setup, include=FALSE}
# Random Intercept + Random Slope (Independent Random Effects)
knitr::opts_chunk$set(echo = TRUE)
library(tictoc)
library(ggplot2)
library(MASS)
library(cli)
library(torch)
library(dplyr)
library(tidyr)
library(ggpubr)
library(zeallot)
```


```{r}
# Helper Functions
sigmoid = function(x){1/(1+exp(-x))}

bernoulli_sampler = function(n, p){as.integer(runif(n) < p)}

JJ_func = function(xi){
  ans = (torch_sigmoid(xi)-1/2)/(2*xi)
  ans[torch_isnan(ans)] = 1/8
  ans 
}

torch_cholesky_R = function(M){
  X = as_array(M)
  if (length(dim(X)) == 2){
    return(torch_tensor(t(chol(X))))
  }
  if (length(dim(X)) == 3){
    res = torch_zeros(dim(X))
    for (i in 1:dim(X)[1]){
      res[i,,] = t(chol(X[i,,]))
    }
    return(res)
  }
}

transpose = function(M){return(M$permute(c(2,1)))}

torch_vec = function(M){return((M$permute(c(2,1)))$reshape(-1))}

torch_kronecker = function(M, N){
  return(torch_tensor(kronecker(as_array(M), as_array(N))))
}

torch_outer_batch = function(M, N = NULL){
  # M has dimension A*B, N has dimension A*C, the outer has dimension A*B*C
  # If N is not provided, then N = M
  if (is.null(N)){N = M}
  torch_einsum("ab,ac->abc", list(M, N))
}

intToBin = function(x, d){
  if (x == 0){res = c(0)}
  if (x >= 2^d){stop("x should be in [0, 2^d-1]")}
  res = c()
  while (x > 1){
    res = c(x %% 2, res)
    x = x %/% 2
  }
  if (x == 1){res = c(x, res)}
  if (length(res) < d){res = c(rep(0, d-length(res)), res)}
  return(paste(res, collapse=""))
}

E_Z_skill_to_all = function(E_Z_K, A_K){
  c(N, K, indT) %<-% E_Z_K$shape
  indT = log(indT, 2)
  E_Z = torch_ones(N, 2^(K*indT))
  for (i in 1:2^(K*indT)){
    for(k in 1:K){
      E_Z[,i] = E_Z[,i]*E_Z_K[,k,as.numeric(A_K[i,k])]
    }  
  }
  return(E_Z)
}

E_Z_all_to_time = function(E_Z, A_T){
  indT = A_T$shape[2]
  K = log(A_T$shape[1], 2)/indT
  N = E_Z$shape[1]
  E_Z_T = torch_zeros(N, indT, 2^K)
  for (t in 1:indT){
    for (k in 1:(2^K)){
      E_Z_T[,t,k] = E_Z[,A_T[,t] == k]$sum(2)
    }
  }  
  return(E_Z_T)
}

E_Z_all_to_skill = function(E_Z, A_K){
  K = A_K$shape[2]
  indT = log(A_K$shape[1], 2)/K
  N = E_Z$shape[1]
  E_Z_T = torch_zeros(N, K, 2^indT)
  for (k in 1:K){
    for (p in 1:(2^indT)){
      E_Z_T[,k,p] = E_Z[,A_K[,k] == p]$sum(2)
    }
  }  
  return(E_Z_T)
}

generate_beta = function(d){
  if (d == 2){
    beta = c(-2.5, 4.5)
  }else if (d == 4){
    beta = c(-2.5, 2, 2, 1)
  }else if (d == 8){
    beta = c(-2.5, 1, 1, 0.8, 1, 0.8, 0.8, 0.5)
  }else{
    stop("Invalid d")
  }
  beta
}

generate_delta_matrix = function(Q, K){
  calculate_q = function(t, q){prod(sapply(1:length(q), function(i){ifelse(substr(t,i,i) == '1', q[i], 1)}))}
  calculate_delta = function(q){
    t = sapply(0:(2^K-1), function(i){intToBin(i, d = K)})
    Q_res = matrix(rep(sapply(t, function(x){calculate_q(x, q)}), 2^K), ncol = 2^K, byrow = T, dimnames = list(t,t))
    A_res = matrix(unlist(lapply(t, function(y){sapply(t, function(x){calculate_q(x, sapply(1:K, function(i){as.numeric(substr(y,i,i))}))})})), ncol = 2^K, byrow = T, dimnames = list(t,t))
    A_res*Q_res 
  }
  
  J = nrow(Q)
  delta_matrix = lapply(1:J, function(j){calculate_delta(Q[j,])})
  valid_cols = lapply(1:J, function(j) names(which(colSums(delta_matrix[[j]])>0)))
  # valid_cols = lapply(valid_cols, function(x){x[-1]})
  for (j in 1:J){
    delta_matrix[[j]] = matrix((delta_matrix[[j]][,valid_cols[[j]]]), nrow = 2^K, dimnames = c(list(rownames(delta_matrix[[1]])), list(valid_cols[[j]])))
  }
  return(delta_matrix)
}

array_to_tensor = function(list_of_arrays){
  K = length(list_of_arrays)
  indT = length(list_of_arrays[[1]])
  for (k in 1:K){
    for (t in 1:indT){
      list_of_arrays[[k]][[t]] = torch_tensor(list_of_arrays[[k]][[t]])
      if (length((dim(list_of_arrays[[k]][[t]]))) == 1){
        list_of_arrays[[k]][[t]] = list_of_arrays[[k]][[t]]$unsqueeze(-1)
      }
    }
  }
  list_of_arrays
}

tensor_to_array = function(list_of_tensors){
  K = length(list_of_tensors)
  indT = length(list_of_tensors[[1]])
  for (k in 1:K){
    for (t in 1:indT){
      list_of_tensors[[k]][[t]] = as_array(list_of_tensors[[k]][[t]])
    }
  }
  list_of_tensors
}
```


```{r}
# Input
# N_per_group: Number of respondents per group, (N is the sum of N_per_group across all groups)
# K: Number of skills
# J: Number of items
# C: Number of groups
# indT: Number of time points
# seed: Random seed
# rand_N: Whether to randomly generate the number of respondents per group
# rand_cor: Correlation between the random effects

# Output
# Y: response matrix with dim = N*indT*J
# X_ind: nested list of individual covariates matrix with dim = N*M, the outer list has length K, the inner list has length indT (then M = 1 when indT = 1)
# X_group: nested list of group covariates matrix with dim = C*D, the outer list has length K, the inner list has length indT
# group: index of group for each respondent
# Q_matrix: Q-matrix with dim = J*K
# profiles_index: index of profiles for each respondent, should be a number between 1 and 2^(K*indT)
# profiles: profiles for each respondent, multidimensional array with dim = N*K*indT
# beta: true beta, list of length K
# gamma: true transition parameters, nested list, the outer list has length K, the inner list has length indT, the dimension of gamma[[k]][[t]] is C when t = 1, and 2*C*M(including 2 sets of parameters) when t > 1
# omega: true group level parameters, nested list, the outer list has length K, the inner list has length indT, the dimension of omega[[k]][[t]] is D when t = 1, and 2*D*M(including 2 sets of parameters) when t > 1

data_generate = function(N_per_group = 20, K = 2, J = 20, C = 10, indT  = 2, seed = 1, rand_N = F, rand_cor = 0.8){
  torch_manual_seed(seed = seed)
  NC = if(rand_N){torch_randint(low = N_per_group, high = 1.5*N_per_group, size = C)}else{torch_full(size = C, fill = N_per_group)}
  N = as.numeric(NC$sum())
  
  # Generate Q-Matrix
  Q_matrix = sapply(as_array(torch_randint(low = 1, high = 2^K, size = J)), function(x){intToBin(x, K)})
  Q_matrix = unname(t(sapply(Q_matrix, function(x){sapply(1:K, function(i){as.numeric(substr(x,i,i))})})))
  
  # Generate Delta Matrix
  delta_matrix = generate_delta_matrix(Q_matrix, K)
  
  # Generate Beta
  beta = lapply(1:J, function(j) torch_tensor(generate_beta(2^sum(Q_matrix[j,]))))
  
  # Generate Group Covariates
  group = unlist(lapply(1:C, function(c){rep(c, as.numeric(NC[c]))}))
  group_mat = torch_sparse_coo_tensor(torch_vstack(list(torch_arange(start = 1, end = N), torch_tensor(group)))$to(dtype = torch_int32()), torch_ones(size = N))
  X_group = torch_cat(list(torch_ones(size = C)$unsqueeze(2), torch_bernoulli(torch_ones(size = C)*0.5)$unsqueeze(2), (torch_rand(size = C)*4+1)$unsqueeze(2)), dim = 2)
  X_group = lapply(1:K, function(k){lapply(1:indT, function(t) X_group)})
  
  # Generate Invididual Covariates
  X_ind = torch_cat(list(torch_ones(size = N)$unsqueeze(2), torch_bernoulli(torch_ones(size = N)*0.5)$unsqueeze(2)), dim = 2)
  X_ind = lapply(1:K, function(k){c(torch_ones(N), lapply(2:indT, function(t) X_ind))})
  
  # Generate Omega
  omega = lapply(1:K, function(k) c(torch_tensor(c(-1.5, 0.5, -0.1)), lapply(1:(indT-1), function(t){torch_cat(list(torch_tensor(cbind(c(-2, 0.5, -0.1), c(4, 1, -0.2)))$unsqueeze(1), torch_tensor(cbind(c(-1.5, 0.5, -0.2), c(3.5, 0.75, -0.15)))$unsqueeze(1)), dim = 1)})))
  
  # Generate Gamma
  Sigma_gamma = lapply(1:K, function(k) c(torch_tensor(0.2), lapply(1:(indT-1), function(t){torch_cat(list(torch_tensor(c(0.2, 0.4))$outer(torch_tensor(c(0.2, 0.4)))*torch_tensor(matrix(c(1, rand_cor, rand_cor, 1), 2))$unsqueeze(1), torch_tensor(c(0.1, 0.2))$outer(torch_tensor(c(0.1, 0.2)))*torch_tensor(matrix(c(1, rand_cor, rand_cor, 1), 2))$unsqueeze(1)), dim = 1)})))
  
  generate_gamma = function(k, t){
    if (t == 1){
      return(X_group[[k]][[t]]$matmul(omega[[k]][[t]])+torch_randn(C)*Sigma_gamma[[k]][[t]])
    }
    else{
      return(X_group[[k]][[t]]$matmul(omega[[k]][[t]])+torch_cat(list(distr_multivariate_normal(torch_zeros(2), Sigma_gamma[[k]][[t]][1,,])$sample(C)$unsqueeze(1), distr_multivariate_normal(torch_zeros(2), Sigma_gamma[[k]][[t]][2,,])$sample(C)$unsqueeze(1)), dim =1))
    }
  }
  
  gamma = lapply(1:K, function(k) lapply(1:indT, function(t) generate_gamma(k = k, t = t)))
  
  # Generate Profiles
  A = lapply(0:(2^(K*indT)-1), function(x){torch_tensor(matrix(as.integer(strsplit(intToBin(x, K*indT), "")[[1]]), ncol = indT, byrow = T))})
  A = torch_cat(lapply(A, function(x){x$unsqueeze(1)}), dim = 1) 
  
  prob_all = torch_zeros(N, 2^(K*indT))
  for (i in 1:A$shape[1]){
    profile = as_array(A[i,,])
    prob = torch_ones(N)
    for (k in 1:K){
      prob = prob*((X_ind[[k]][[1]]*group_mat$matmul(gamma[[k]][[1]]))*(2*profile[k,1]-1))$sigmoid()
      for (t in 2:indT){
        if (profile[k,t-1] == 0){
          gamma_tk = gamma[[k]][[t]][1,,]
        }
        else{
          gamma_tk = gamma[[k]][[t]][2,,]
        }
        prob = prob*(((X_ind[[k]][[t]]*group_mat$matmul(gamma_tk))$sum(2)*(2*profile[k,t]-1))$sigmoid())
      }
    }
    prob_all[,i] = prob
  }
  
  profiles_index = distr_categorical(prob_all)$sample()$squeeze() # index of profiles
  profiles = A[profiles_index,,]$float() # dim = (N, K, T)
  
  # Generate Response Matrix Y
  Y = torch_zeros(N, indT, J)
  for (t in 1:indT){
    for(j in 1:J){
      Y[,t,j] = torch_bernoulli(torch_tensor(delta_matrix[[j]][as.numeric(profiles[,,t]$matmul(torch_tensor(2^((K-1):0)))+1),])$matmul(beta[[j]])$sigmoid())
    }
  }
  
  list('Y' = as_array(Y), 'X_group' = tensor_to_array(X_group), 'X_ind' = tensor_to_array(X_ind), 'group' = group, 'profiles' = as_array(profiles), 'profiles_index' = as.numeric(profiles_index), 'beta' = lapply(beta, function(x) as_array(x)), 'Q_matrix' = Q_matrix, 'omega' = tensor_to_array(omega), 'gamma' = tensor_to_array(gamma))
}

data = data_generate(N_per_group = 100, K = 2, J = 25, C = 50, indT = 2, seed = 1, rand_N = F, rand_cor = 0)
```


```{r}
VB_TCDM_Random_Ind_fit = function(data, max_iter = 100, min_iter = 50){
  Y = torch_tensor(data$Y)
  c(N, indT, J) %<-% Y$shape
  K = ncol(data$Q_matrix)
  delta_matrix = lapply(generate_delta_matrix(data$Q_matrix, K), function(x) torch_tensor(x)$float())
  group = data$group
  group_mat = torch_sparse_coo_tensor(torch_vstack(list(torch_arange(start = 1, end = N), torch_tensor(group)))$to(dtype = torch_int32()), torch_ones(size = N))
  X_group = array_to_tensor(data$X_group)
  X_ind = array_to_tensor(data$X_ind)
  C = X_group[[1]][[1]]$shape[1]
  beta_dim = 2^rowSums(data$Q_matrix)
  A = lapply(0:(2^(K*indT)-1), function(x){torch_tensor(matrix(as.integer(strsplit(intToBin(x, K*indT), "")[[1]]), ncol = indT, byrow = T))})
  A = torch_cat(lapply(A, function(x){x$unsqueeze(1)}), dim = 1)$float()
  A_T = transpose(A$permute(c(3,1,2))$matmul(torch_tensor(2^((K-1):0)))+1)
  A_K = transpose(A$permute(c(2,1,3))$matmul(torch_tensor(2^((indT-1):0)))+1)
    
  # Initialize Beta
  M_beta_init = lapply(beta_dim, function(x) torch_zeros(x))
  M_beta = lapply(beta_dim, function(x) torch_zeros(x))
  V_beta_init = lapply(beta_dim, function(x) torch_eye(x))
  V_beta = lapply(beta_dim, function(x) torch_eye(x))
  F_beta = torch_tensor(t(sapply(1:J, function(j){as_array(torch_matmul(delta_matrix[[j]], M_beta[[j]]))})))
  F2_beta = torch_tensor(t(sapply(1:J, function(j){as_array(torch_sum(torch_matmul(delta_matrix[[j]], torch_cholesky(V_beta[[j]]+torch_outer(M_beta[[j]], M_beta[[j]])))^2, dim = 2))})))
  
  # Initialize Gamma
  # M_gamma = lapply(1:K, function(k) c(torch_zeros(C, X_ind[[k]][[1]]$shape[2]), lapply(2:indT, function(t) torch_zeros(2, C, X_ind[[k]][[t]]$shape[2]))))
  M_gamma = lapply(1:K, function(k) c(-2*torch_ones(C, X_ind[[k]][[1]]$shape[2]), lapply(2:indT, function(t) torch_zeros(2, C, X_ind[[k]][[t]]$shape[2]))))
  V_gamma = lapply(1:K, function(k) c(torch_diag_embed(torch_ones(C,X_ind[[k]][[1]]$shape[2])), lapply(2:indT, function(t) torch_diag_embed(torch_ones(2, C, X_ind[[k]][[t]]$shape[2])))))
  E_gamma_tgamma = list(torch_zeros(N, K), torch_zeros(2, N, indT-1, K))
  for (k in 1:K){
    E_gamma_tgamma[[1]][,k] = group_mat$matmul(M_gamma[[k]][[1]]$squeeze()^2+V_gamma[[k]][[1]][,1,1])
    for (t in 2:indT){
      for (z in 1:2){
        E_gamma_tgamma[[2]][z,,t-1,k] = (torch_sum((X_ind[[k]][[t]]$matmul(torch_cholesky(torch_outer_batch(M_gamma[[k]][[t]][z,,])+V_gamma[[k]][[t]][z,,,])))^2, 3)*transpose(group_mat))$sum(1)$to_dense()
      }
    }
  }
  
  # Initialize Omega
  M_omega_init = lapply(1:K, function(k) c(torch_zeros(X_ind[[k]][[1]]$shape[2], X_group[[k]][[1]]$shape[2]), lapply(2:indT, function(t) torch_zeros(2, X_ind[[k]][[t]]$shape[2], X_group[[k]][[t]]$shape[2]))))
  M_omega = lapply(1:K, function(k) c(torch_zeros(X_ind[[k]][[1]]$shape[2], X_group[[k]][[1]]$shape[2]), lapply(2:indT, function(t) torch_zeros(2, X_ind[[k]][[t]]$shape[2], X_group[[k]][[t]]$shape[2]))))
  
  V_omega_init = lapply(1:K, function(k) c(torch_diag_embed(torch_ones(X_ind[[k]][[1]]$shape[2],X_group[[k]][[t]]$shape[2])), lapply(2:indT, function(t) torch_diag_embed(torch_ones(2, X_ind[[k]][[t]]$shape[2], X_group[[k]][[t]]$shape[2])))))
  V_omega = lapply(1:K, function(k) c(torch_diag_embed(torch_ones(X_ind[[k]][[1]]$shape[2],X_group[[k]][[t]]$shape[2])), lapply(2:indT, function(t) torch_diag_embed(torch_ones(2, X_ind[[k]][[t]]$shape[2], X_group[[k]][[t]]$shape[2])))))
  
  
  # V_omega_init = lapply(1:K, function(k) c(torch_eye(X_group[[k]][[1]]$shape[2]), lapply(2:indT, function(t) torch_diag_embed(torch_ones(2, X_group[[k]][[t]]$shape[2])))))
  # V_omega = lapply(1:K, function(k) c(torch_eye(X_group[[k]][[1]]$shape[2]*X_ind[[k]][[1]]$shape[2]), lapply(2:indT, function(t) torch_diag_embed(torch_ones(2, X_group[[k]][[t]]$shape[2]*X_ind[[k]][[t]]$shape[2])))))
  
  # Initialize Z
  E_Z_K = torch_ones(N, K, 2^indT)/2^indT
  E_Z = E_Z_skill_to_all(E_Z_K = E_Z_K, A_K = A_K)
  E_Z_T = E_Z_all_to_time(E_Z = E_Z, A_T = A_T)
  
  # Initialize Tau
  sigma_tau_init = 1e-3
  a_tau_init = lapply(1:K, function(k){c(torch_ones(1, X_ind[[k]][[1]]$shape[2])/2*sigma_tau_init, lapply(2:indT, function(t){torch_ones(2, X_ind[[k]][[t]]$shape[2])/2*sigma_tau_init}))})
  a_tau = lapply(1:K, function(k){c(torch_ones(1, X_ind[[k]][[1]]$shape[2])/2*sigma_tau_init, lapply(2:indT, function(t){torch_ones(2, X_ind[[k]][[t]]$shape[2])/2*sigma_tau_init}))})
  b_tau_init = lapply(1:K, function(k){c(torch_ones(1, X_ind[[k]][[1]]$shape[2])/2*sigma_tau_init, lapply(2:indT, function(t){torch_ones(2, X_ind[[k]][[t]]$shape[2])/2*sigma_tau_init}))})
  b_tau = lapply(1:K, function(k){c(torch_ones(1, X_ind[[k]][[1]]$shape[2])/2*sigma_tau_init, lapply(2:indT, function(t){torch_ones(2, X_ind[[k]][[t]]$shape[2])/2*sigma_tau_init}))})
  E_tau_inv = lapply(1:K, function(k){lapply(1:indT, function(t){a_tau[[k]][[t]]/b_tau[[k]][[t]]})})
    
  # Initialize Auxiliary Variables
  xi = torch_zeros(J, 2^K)
  eta = list(torch_zeros(N, K), torch_zeros(2, N, indT-1, K))
  xi = torch_tensor(t(sapply(1:J, function(j) as_array(torch_sqrt(torch_diag(delta_matrix[[j]]$matmul(V_beta[[j]]+M_beta[[j]]$outer(M_beta[[j]]))$matmul(transpose(delta_matrix[[j]]))))))))
  for (k in 1:K){
    eta[[1]][,k] = torch_sqrt(group_mat$matmul(M_gamma[[k]][[1]]$squeeze()^2+V_gamma[[k]][[1]][,1,1]))
    for (t in 2:indT){
      for (z in 1:2){
        eta[[2]][z,,t-1,k] = torch_sqrt((torch_sum((X_ind[[k]][[t]]$matmul(torch_cholesky(torch_outer_batch(M_gamma[[k]][[t]][z,,])+V_gamma[[k]][[t]][z,,,])))^2, 3)*transpose(group_mat))$sum(1)$to_dense())
      }
    }
  }
  
  cli_progress_bar()
  for (iter_ in 1:max_iter){
      # Update E_Z_K
    E_Z_K_log = torch_zeros(N, K, 2^indT)
    
    for (k in 1:K){
      for (p in 1:2^indT){
        profile_k = as.integer(strsplit(intToBin(p-1, indT), "")[[1]])
        prob = torch_zeros(N)
        prob = prob + eta[[1]][,k]$sigmoid()$log()-eta[[1]][,k]/2-JJ_func(eta[[1]][,k])*(E_gamma_tgamma[[1]][,k]-eta[[1]][,k]^2)+group_mat$matmul(M_gamma[[k]][[1]]$squeeze())*(profile_k[1]-0.5)
        for (t in 2:indT){
          if (profile_k[t-1]==0){
            prob = prob + eta[[2]][1,,t-1,k]$sigmoid()$log()-eta[[2]][1,,t-1,k]/2-JJ_func(eta[[2]][1,,t-1,k])*(E_gamma_tgamma[[2]][1,,t-1,k]-eta[[2]][1,,t-1,k]^2)+(group_mat$matmul(M_gamma[[k]][[t]][1,,])*X_ind[[k]][[t]])$sum(2)*(profile_k[t]-0.5)
          }
          else if (profile_k[t-1]==1){
            prob = prob + eta[[2]][2,,t-1,k]$sigmoid()$log()-eta[[2]][2,,t-1,k]/2-JJ_func(eta[[2]][2,,t-1,k])*(E_gamma_tgamma[[2]][2,,t-1,k]-eta[[2]][2,,t-1,k]^2)+(group_mat$matmul(M_gamma[[k]][[t]][2,,])*X_ind[[k]][[t]])$sum(2)*(profile_k[t]-0.5)
          }
        }
        E_Z_K_log[,k,p] = prob*1.0
      }
    }
    
    calculate_prob = function(skill_k, m){
      res = torch_ones(N)
      for (k in 1:K){
        if (k != skill_k){
          res = res*E_Z_K[,k,as.numeric(A_K[m,k])]
        }
      }
      return(res)
    }
    
    y_tilde = torch_zeros(N, indT, J, 2^K)
    for (l in 1:2^K){
      y_tilde[,,,l] = (Y-1/2)*F_beta[,l]+(xi$sigmoid()$log()-xi/2-JJ_func(xi)*(F2_beta-xi^2))[,l]
    }
    y_tilde = y_tilde$sum(3)
    
    for(k in 1:K){
      temp_prob_1 = torch_zeros(N, 2^(K*indT))
      temp_prob_2 = torch_zeros(N, 2^(K*indT))
      for(m in 1:2^(K*indT)){
        temp_prob_2[,m] = calculate_prob(k, m)
        tmp = torch_zeros(N)
        for (t in 1:indT){
          tmp = tmp+y_tilde[,t,as.numeric(A_T[m,t])]
        }
        temp_prob_1[,m] = tmp
      }
      temp_prob = temp_prob_1*temp_prob_2
      for (p in 1:2^indT){
        E_Z_K_log[,k,p] = E_Z_K_log[,k,p]+temp_prob[,A_K[,k] == p]$sum(2)
      }
      E_Z_K[,k,] = nnf_softmax(E_Z_K_log[,k,], 2)
    }
    # E_Z_K = nnf_softmax(E_Z_K_log, 3)
    E_Z = E_Z_skill_to_all(E_Z_K, A_K)
    E_Z_T = E_Z_all_to_time(E_Z, A_T)
    
    # Update Beta
    V_beta = lapply(1:J, function(j){torch_inverse(torch_inverse(V_beta_init[[j]])+2*transpose(delta_matrix[[j]])$matmul(torch_diag(E_Z_T$sum(c(1,2))*JJ_func(xi[j,])))$matmul(delta_matrix[[j]]))})
    M_beta = lapply(1:J, function(j){V_beta[[j]]$matmul(torch_inverse(V_beta_init[[j]])$matmul(M_beta_init[[j]])+transpose(delta_matrix[[j]])$matmul(torch_einsum("ntl,nt->l", list(E_Z_T, Y[,,j]-1/2))))})
    F_beta = torch_tensor(t(sapply(1:J, function(j){as_array(torch_matmul(delta_matrix[[j]], M_beta[[j]]))})))
    F2_beta = torch_tensor(t(sapply(1:J, function(j){as_array(torch_sum(torch_matmul(delta_matrix[[j]], torch_cholesky(V_beta[[j]]+torch_outer(M_beta[[j]], M_beta[[j]])))^2, dim = 2))})))
    
    # Update Gamma
    for (k in 1:K){
      tmp = sapply(1:2^indT-1, function(x){as.integer(strsplit(intToBin(x, indT), "")[[1]])})
      V_gamma[[k]][[1]][,1,1] = 1/(a_tau[[k]][[1]]/b_tau[[k]][[1]]+2*transpose(group_mat)$matmul(JJ_func(eta[[1]][,k])))
      M_gamma[[k]][[1]][,1] = V_gamma[[k]][[1]][,1,1]*((a_tau[[k]][[1]]/b_tau[[k]][[1]]*X_group[[k]][[1]]$matmul(transpose(M_omega[[k]][[1]])))$squeeze()+transpose(group_mat)$matmul(E_Z_K[,k,])$matmul(torch_tensor(tmp[1,]-1/2)))
    }
    
    for(k in 1:K){
      for (t in 2:indT){
        for (z in 0:1){
          tmp = sapply(1:2^indT-1, function(x){as.integer(strsplit(intToBin(x, indT), "")[[1]])})
          V_gamma[[k]][[t]][z+1,,,] = torch_inverse(torch_diag(a_tau[[k]][[t]][z+1,]/b_tau[[k]][[t]][z+1,])+2*(transpose(group_mat)$matmul(torch_einsum("n,nmc->nmc", list(JJ_func(eta[[2]][z+1,,t-1,k])*E_Z_K[,k,]$matmul(torch_tensor(tmp[t-1,] == z)$float()),torch_outer_batch(X_ind[[k]][[t]])))$permute(c(3,1,2))))$permute(c(2,1,3)))
          M_gamma[[k]][[t]][z+1,,] = torch_einsum("nmc, nc->nm", list(V_gamma[[k]][[t]][z+1,,,], X_group[[k]][[t]]$matmul(transpose(torch_diag(a_tau[[k]][[t]][z+1,]/b_tau[[k]][[t]][z+1,])$matmul(M_omega[[k]][[t]][z+1,])))+transpose(group_mat)$matmul(torch_einsum("n,nm->nm", list(E_Z_K[,k,]$matmul(torch_tensor((tmp[t-1,] == z)*(tmp[t,]-1/2))), X_ind[[k]][[t]])))))
        }
      }
    }
    
    E_gamma_tgamma = list(torch_zeros(N, K), torch_zeros(2, N, indT-1, K))
    for (k in 1:K){
      E_gamma_tgamma[[1]][,k] = group_mat$matmul(M_gamma[[k]][[1]]$squeeze()^2+V_gamma[[k]][[1]][,1,1])
      for (t in 2:indT){
        for (z in 1:2){
          E_gamma_tgamma[[2]][z,,t-1,k] = (torch_sum((X_ind[[k]][[t]]$matmul(torch_cholesky(torch_outer_batch(M_gamma[[k]][[t]][z,,])+V_gamma[[k]][[t]][z,,,])))^2, 3)*transpose(group_mat))$sum(1)$to_dense()
        }
      }
    }
  
    # Update Omega
    for(k in 1:K){
      for (m in 1:X_ind[[k]][[1]]$shape[2]){
        V_omega[[k]][[1]][m,,] = torch_inverse(V_omega_init[[k]][[1]][m,,]$inverse()+a_tau[[k]][[1]][1,m]/b_tau[[k]][[1]][1,m]*transpose(X_group[[k]][[1]])$matmul(X_group[[k]][[1]]))
        M_omega[[k]][[1]][m,] = V_omega[[k]][[1]][m,,]$matmul(V_omega_init[[k]][[1]][m,,]$inverse()$matmul(M_omega_init[[k]][[1]][m,])+(a_tau[[k]][[1]][m,]/b_tau[[k]][[1]][m,])*transpose(X_group[[k]][[1]])$matmul(M_gamma[[k]][[1]][,m]))
      }
      
      for (m in 1:X_ind[[k]][[t]]$shape[2]){
        for(t in 2:indT){
          for(z in 1:2){
            V_omega[[k]][[t]][z,m,,] = torch_inverse(V_omega_init[[k]][[t]][z,m,,]$inverse()+a_tau[[k]][[t]][z,m]/b_tau[[k]][[t]][z,m]*transpose(X_group[[k]][[t]])$matmul(X_group[[k]][[t]]))
            M_omega[[k]][[t]][z,m,] = V_omega[[k]][[t]][z,m,,]$matmul(V_omega_init[[k]][[t]][z,m,,]$inverse()$matmul(M_omega_init[[k]][[t]][z,m,])+(a_tau[[k]][[t]][z,m]/b_tau[[k]][[t]][z,m])*transpose(X_group[[k]][[t]])$matmul(M_gamma[[k]][[t]][z,,m]))
          }
        }
      }
    }
  
    # Update Tau
    for (k in 1:K){
      for (m in 1: X_ind[[k]][[1]]$shape[2]){
        a_tau[[k]][[1]][1,m] = a_tau_init[[k]][[1]][1,m]+C/2
        b_tau[[k]][[1]][1,m] = b_tau_init[[k]][[1]][1,m]+(M_gamma[[k]][[1]][,m]^2+V_gamma[[k]][[1]][,m,m]-2*X_group[[k]][[1]]$matmul(M_omega[[k]][[1]][m,])*M_gamma[[k]][[1]][,m]+((X_group[[k]][[1]]$matmul(torch_cholesky_R(M_omega[[k]][[1]][m,]$outer(M_omega[[k]][[1]][m,])+V_omega[[k]][[1]][m,,])))^2)$sum(2))$sum()/2
      }
      
      for (t in 2:indT){
        for (z in 1:2){
          for (m in 1: X_ind[[k]][[t]]$shape[2]){
            a_tau[[k]][[t]][z,m] = a_tau_init[[k]][[t]][z,m]+C/2
            b_tau[[k]][[t]][z,m] = b_tau_init[[k]][[t]][z,m]+(M_gamma[[k]][[t]][z,,m]^2+V_gamma[[k]][[t]][z,,m,m]-2*X_group[[k]][[t]]$matmul(M_omega[[k]][[t]][z,m,])*M_gamma[[k]][[t]][z,,m]+((X_group[[k]][[t]]$matmul(torch_cholesky_R(M_omega[[k]][[t]][z,m,]$outer(M_omega[[k]][[t]][z,m,])+V_omega[[k]][[t]][z,m,,])))^2)$sum(2))$sum()/2
          }
        }
      }
    }
    
    xi = F2_beta$sqrt()
    
    eta = list(E_gamma_tgamma[[1]]$sqrt(), E_gamma_tgamma[[2]]$sqrt())
    
    cli_progress_update()
  }
  E_tau = lapply(1:K, function(k){lapply(1:indT, function(t){(b_tau[[k]][[t]]/(a_tau[[k]][[t]]-1))^0.5})})
  return(list('beta' = M_beta, 'gamma' = M_gamma, 'omega' = M_omega, 'tau' = E_tau, 'profiles' = as_array(E_Z$max(2)[[2]])))
}
```

```{r}
res = VB_TCDM_Random_Ind_fit(data)
```



```{r}
plot(as_array(res$gamma[[1]][[1]]), data$gamma[[1]][[1]])
abline(0,1)

plot(as_array(res$gamma[[1]][[2]][1,,1]), data$gamma[[1]][[2]][1,,1])
abline(0,1)

plot(as_array(res$gamma[[1]][[2]][2,,1]), data$gamma[[1]][[2]][2,,1])
abline(0,1)

plot(as_array(res$gamma[[1]][[2]][1,,2]), data$gamma[[1]][[2]][1,,2])
abline(0,1)

plot(as_array(res$gamma[[1]][[2]][2,,2]), data$gamma[[1]][[2]][2,,2])
abline(0,1)

plot(as_array(res$gamma[[2]][[2]][1,,2]), data$gamma[[2]][[2]][1,,2])
abline(0,1)
```


```{r}
mean(res$profiles == data$profiles_index)
```

```{r}
plot(unlist(data$beta), unlist(lapply(res$beta, function(x){as_array(x)})))
abline(a=0, b=1)
```


```{r}
res$tau
```


```{r}
K = 2
indT = 2
par(mfrow=c(K, indT))
for (k in 1:K){
  plot(res$omega[[k]][[1]], data$omega[[k]][[1]])
  abline(0, 1)
  for (t in 2:indT){
    plot(res$omega[[k]][[t]],torch_tensor(data$omega[[k]][[t]])$permute(c(1,3,2)))
    abline(0,1)
  }
}
```










